#!/bin/sh

nudjDirectory=$1

validEnvironment() {
  [ "$1" = "local" ] || \
  [ "$1" = "development" ] || \
  [ "$1" = "demo" ] || \
  [ "$1" = "staging" ] || \
  [ "$1" = "production" ]
}

target=$2
if [ -z "$2" ]
then
  echo "Must supply a target - e.g. ENV=local"
  exit 1
fi

if ! validEnvironment $target
then
  echo "Must supply a valid target - local|development|demo|staging|production"
  exit 1
fi

script=$3
if [ -z "$3" ]
then
  echo "Must supply a script name - e.g. SCRIPT=00000-export-role-tags"
  exit 1
fi

echo "Executing $script on $target"

if [[ "$target" = "development" || "$target" = "demo" || "$target" = "staging" || "$target" = "production" ]]; then
  server="nudj$target"

  echo "local: Syncing devops scripts to $target"
  rsync -az --delete -e "ssh" $PWD/tasks/remote/ $server:/home/nudjtech/devops
  exitCode=$?

  if [ $exitCode = 0 ]
  then
    echo "local: Executing script on $target"
    ssh -T $server /bin/sh -c "'/home/nudjtech/devops/execute $target $script'"
    exitCode=$?
  fi
else
  echo "local: Executing script locally"
  $PWD/tasks/local/execute "$script" "$nudjDirectory/api/src/scripts"
  exitCode=$?
fi

[[ $exitCode = 0 ]] && result="complete 👍" || result="failed 👎"
echo "local: Execution of $script on $target $result"
