#!/bin/sh

validEnvironment() {
  [ "$1" = "local" ] || \
  [ "$1" = "test" ] || \
  [ "$1" = "development" ] || \
  [ "$1" = "staging" ]
}

target=$1
if [ -z "$target" ]
then
  echo "Must supply a target - e.g. TARGET=local"
  exit 1
fi

if ! validEnvironment $target
then
  echo "Must supply a valid target - local|test|development|staging"
  exit 1
fi

type=${2:-latest}

echo "Migration of type $type on $target"
$PWD/tasks/local/migrate $target $type
exitCode=$?

[[ $exitCode = 0 ]] && result="complete 👍" || result="failed 👎"
echo "local: Migration of type $type on $target $result"
