#!/bin/sh

environment=$1
baseDir='/Users/nick/dev/nudj'
dockerRun="docker-compose -p nudj -f $PWD/local/server/docker-compose.yml -f $PWD/local/web/docker-compose.yml -f $PWD/local/hire/docker-compose.yml -f $PWD/local/admin/docker-compose.yml -f $PWD/local/api/docker-compose.yml run --rm"
devopsDir="$baseDir/devops/src/scripts/remote"
outputDir="$baseDir/backups/$environment/$(date '+%F')"

cd $environment

echo "$environment: Fetching db connection variables from envkey"
dbEnvVars=$($dockerRun -v $devopsDir/api:/usr/src/devops api node /usr/src/devops/extract-envkeys DB_HOST DB_PORT DB_NAME DB_USER DB_PASS)

echo "$environment: Executing backup script on db service"
$dockerRun -v $devopsDir/db:/devops -v $outputDir:/dbdump $dbEnvVars db /devops/backup
