#!/bin/sh

devopsDir="/Users/nick/dev/nudj/devops/src/tasks/remote"
outputDir="/Users/nick/dev/nudj/backups/local/$(date '+%F')"

echo "local: Fetching db connection variables from envkey"
dbEnvVars=$(docker-compose -p nudj run --rm -v $devopsDir/api:/usr/src/devops api node /usr/src/devops/extract-envkeys DB_HOST DB_PORT DB_NAME DB_USER DB_PASS)

echo "local: Executing backup script on db service"
docker-compose -p nudj run --rm -v $devopsDir/db:/devops -v $outputDir:/dbdump $dbEnvVars db /devops/backup
